### ISSUE TITLE
Fix/Remove/Clarify Lead Color-Coding on Hardware README

### ISSUE THREAD

**Issue by BigThunderSR** [esphome-econet/esphome-econet#119]
Unfortunately, I'm not getting any data for this model: PROPH50 T2 RH350 DCB

All parts were bought from Mouser via provided links. I have verified that the cable conducts from the TTL plug to the RJ11 connector using a multimeter.

**Comment by barndawgie** [comment]
When you say "not getting any data" you mean that in the logs you're not seeing any data coming back on any of the datapoints?

Usually this means your wires are not corrected to the right connectors. Do NOT trust the colors as it seems like they are not consistent between cables. Can you verify that you have RJ11 Pin 3 going to B, Pin 4 going to A, and Ping 5 going GND as shown in the diagram at https://github.com/esphome-econet/esphome-econet#hardware-installation ?

**Comment by barndawgie** [comment]
Yeah, your wires on your plug are different colors than what's show in the diagram. It looks like you need to go:
Green -> B
Red -> A
Black -> Ground

**Comment by barndawgie** [comment]
Are the colors indicated on the README wrong for what you expect the standard to be based on that article?

Also, can you confirm that your setup is working now?

**Comment by barndawgie** [comment]
I think the diagram on the README is flipped from the one you shared. Either I read it wrong too or it's flipped :-)

I'll keep this open while we discuss what to change.

**Comment by Linwood-F** [comment]
I was following this as I was waiting for UPS to deliver my hardware; it came, I connected, it worked first try.  I do think that the pins in the documentation may be incorrect based on old school telephone cable.  I found I had purged all my RJ11/12/etc connectors, but found some flat phone cord.  It had the pins reversed from what you showed in terms of colors.  I *THINK* that this may be the difference in RJ9 and RJ11 if this web site is to be believed: [https://forum.huawei.com/enterprise/en/differences-between-rj9-rj11-rj12-rj45-and-rj48/thread/673245715150815232-667213852955258880](url)

Here you can see the colors through the back side.  To me these are reversed, HOWEVER, most documentation calls for RJ11 to be as you show.  So I think (as you already mention) there can be differences in cables and the pinouts are what counts.  I followed that (in my case Red-A, Green-B, Black-G) and it is working great. 

![colors](https://github.com/esphome-econet/esphome-econet/assets/13143855/6449ba3e-9476-4e1e-b3f9-0867cea6867e)
