### ISSUE TITLE
Simplify setup process using Web Installer

### ISSUE THREAD

**Issue by tronikos** [esphome-econet/esphome-econet#123]
See https://esphome.github.io/esp-web-tools/ section "Adding ESP Web Tools to your website"
This can make installation much easier, especially for ATOM since the pins are standard. It's supposed to even setup Wi-Fi using Bluetooth LE (Improv Wi-Fi protocol). I don't have either an ATOM or ESP32 to test it.

Some examples:

https://github.com/tasmota/install
https://tasmota.github.io/install/

https://github.com/ratgdo/esphome-ratgdo
https://ratgdo.github.io/esphome-ratgdo/

**Comment by barndawgie** [comment]
This is now enabled at https://esphome-econet.github.io/
