### ISSUE TITLE
Add Sensor for Rheem Microcontroller Time

### ISSUE THREAD

**Issue by barndawgie** [esphome-econet/esphome-econet#164]
Per discussion in Discord, sounds like it's possible to determine the Rheem Microcontrollers current time: https://discord.com/channels/1148015790038188073/1151284280408948868/1174744288291201094

I think this would be useful to add a Diagnostic Sensor.

**Comment by barndawgie** [comment]
@tronikos - Is this possible with existing code? Or we'd need to expose some additional data from the C layer?

**Comment by tronikos** [comment]
It depends on how it's exposed. Is it available?

**Comment by barndawgie** [comment]
There is no string for it that I'm aware of, but @Daniel-dev22 said he thought it came back on other calls?

**Comment by tronikos** [comment]
There is occasional writes with time, it seems to make sure communicated units are in sync, see https://github.com/esphome-econet/esphome-econet/blob/72d640ad6998cd6d116d10beb045f614f85904ca/components/econet/econet.cpp#L261-L262
I don't think it makes sense to expose that given how infrequent they are. And they are only present if there is a thermostat. It would be better to periodically issue such a write command from our component.
