### ISSUE TITLE
Support Ability to Specify Natural Gas vs Propane for Gas Usage Estimation 

### ISSUE THREAD

**Issue by stockmopar** [esphome-econet/esphome-econet#229]

**Comment by barndawgie** [comment]
@stockmopar Are you able to see anything in logs indicating that there is a sensor we could look at to determine fuel type? If not, we would need to add this a configuration option on the Furnace itself, I guess?

**Comment by stockmopar** [comment]
From investigating, it appears that there is not a setting that is changed during a natural gas to propane conversion. Which tells me the chance of there being a data point for this is very unlikely. Safe to assume we will just need to make this a configuration / substitution.
