### ISSUE TITLE
Add Software Version, Model #, and Serial # for ODUs

### ISSUE THREAD

**Issue by stockmopar** [esphome-econet/esphome-econet#277]
#232

**Comment by justbruce** [comment]
I believe these data points are PRODMODN [Model #] , PRODSERN [Serial #] and SW_VERSN [ODU Software Version]

**Comment by barndawgie** [comment]
@justbruce -  Can you submit a PR for including these in the `econet_hvac_odu.yaml` config?

**Comment by fireheadman** [comment]
Volunteering as a tester for code when it is updated
