### ISSUE TITLE
Software Version sometimes shows Thermostat and sometimes shows WiFi Module 

### ISSUE THREAD

**Issue by stockmopar** [esphome-econet/esphome-econet#279]
Split these into separate datapoints.

**Comment by justbruce** [comment]
I think SW_VERSN is the first example of why target addresses are so handy - multiple devices will emit it when asked, and we have to filter the response by the SRC address.  (Which I assume you know as the author of the targeting code, but just in case ya don't....)

**Comment by stockmopar** [comment]
Does this issue also apply to water heaters?

**Comment by barndawgie** [comment]
As far as I can tell I've never gotten anything other than `WH-HPW5-H6-01-04` from my water heater, no matter how many times I reset the ESP device (and end up requesting the version anew).
