### ISSUE TITLE
Changing the target temperature using an automation (electric usage shifting)

### ISSUE THREAD

**Issue by Ylianst** [esphome-econet/esphome-econet#319]
I have a 80 gallon heat-pump water heater and, in order to save energy and/or shift electrics consumption, I want to change the target temperature using a home assistant automation. I can change the value on the dashboard, but not within an automation. There are many actions, but not the temperature one?

![image](https://github.com/esphome-econet/esphome-econet/assets/1319013/c7f3625a-de61-4f54-8c50-78a2ff5a0609)

Maybe I am missing something. I could use existing actions to turn off the water heater during peek hours, but the best would be to lower the temp during that time.

Thanks in advance for any tips and tricks.

**Comment by barndawgie** [comment]
ESPHome-EcoNet Water Heaters are actually represented as Climate entities in Home Assistant. Try using the Climate->Set Target Temperature service.

**Comment by Ylianst** [comment]
Thanks. I will give it a try.
