### ISSUE TITLE
Furnace: Add OutdoorAirTemperature and SupplyAirTemperature to HWSTATUS parsing

### ISSUE THREAD

**Issue by bitfliq** [esphome-econet/esphome-econet#327]
Adding parsing of the OutdoorAirTemperature and SupplyAirTemperature to HWSTATUS, positions 52/53 and 145/146.

**Comment by justbruce** [comment]
These items are available separately via their own Datapoints......

  What is the utility of duplicating this data?

**Comment by bitfliq** [comment]
The data is already present in HWSTATUS and does not need to be additionally requested on the bus
