### ISSUE TITLE
Remove improv_serial dependency

### ISSUE THREAD

**Issue by tronikos** [esphome-econet/esphome-econet#373]
This is to save on resources and avoid #365
To my understanding we only need this for the builds we offer from our website and once you adopt the device in ESPHome dashboard this is useless.
How about removing it from our config and have the build scripts add it only while building the firmware?

**Comment by barndawgie** [comment]
This is mostly true. Technically it could still be useful for non-web builds (e.g. to collect logs over USB) but that is niche enough that it makes sense to remove.
