### ISSUE TITLE
Error when upgrading with esphome 2024.6 - "ESPHome supports certificate verification only via ESP-IDF"

### ISSUE THREAD

**Issue by Skullitor13** [esphome-econet/esphome-econet#406]
ESP Home is not letting me upgrade with the following error.

INFO ESPHome 2024.6.0
INFO Reading configuration /config/esphome/econet-hpwh2.yaml...
Failed config

At least one platform must be specified for 'ota'; add 'platform: esphome' for original OTA functionality

**Comment by barndawgie** [comment]
This is a breaking change in the new ESPHome:
https://esphome.io/changelog/2024.6.0.html

You can probably work around it with some config magic while we working a fix.
