### ISSUE TITLE
No data in the logs

### ISSUE THREAD

**Issue by rsmanning** [esphome-econet/esphome-econet#412]
I'm pretty new to all this but I followed AAlliieennX's instructions exactly, purchased the recommended hardware, flashed from the github page with "esphome-econet.esphome-econet: github://esphome-econet/esphome-econet/build-yaml/econet-hpwh-esp32.yaml@main" in the packages yaml.  Its a heatpump type water heater so I used the firmware option.

I'm not getting any data back from mine in the logs and triple checked the wires are in the write location and Ohm tested from the phone pins to the screw heads on the phoenix connector that the connection is good.  Its an Econet controller with a 6pin phone jack on the side.
[
![PXL_20240705_233041949](https://github.com/esphome-econet/esphome-econet/assets/52633799/7669b0d6-25ca-4021-bca0-10346bdcb089)
](url)

**Comment by rsmanning** [comment]
Its a Richmond, not sure if that makes a difference but from what I read Rheem makes Richmond and the part numbers cross over.  This is a model: 10E80-HP4D.

**Comment by barndawgie** [comment]
Are you running the ESPHome dashboard? If so, adopt the device and you can try adding this to your config:

```
substitutions:
  logger_level: INFO
```

Then share your logs here.

**Comment by rsmanning** [comment]
My bad, you can delete this.  looking at pictures on the github page for connecting wires I thought I had them right.  Looked like red to red and green to green on the atom (thought that was strange with it labeled 12v) but then I read the pin out text and switched it to A and B, its working now.
