### ISSUE TITLE
apply PR430 to main/econet_heatpump_water_heater.yaml

### ISSUE THREAD

**Issue by samsonusmc** [esphome-econet/esphome-econet#431]
https://github.com/esphome-econet/esphome-econet/pull/430
should fix the same problem on main/econet_heatpump_water_heater.yaml. Looks like it was missed on the last PR

**Comment by tronikos** [comment]
Nothing to fix in econet_heatpump_water_heater.yaml

**Comment by barndawgie** [comment]
Heat Pump Water Heater inherits from Tank Water Heater:
```yaml
packages:
  econet: !include econet_electric_tank_water_heater.yaml
```

So #430 should resolve HPWH issues as well.
