### ISSUE TITLE
Refactor requesting after writing.

### ISSUE THREAD

**Issue by stockmopar** [esphome-econet/esphome-econet#46]
This could cause very close back to back requests being made. This also bypasses the logic of trying to pick a good time to make a request. Since we are making request every 500ms this is probably not needed. But if periodic requests are extended it would be to make this request as soon as its a good time to make the request.

https://github.com/esphome-econet/esphome-econet/blob/1f98c686b6a146fbb2da36617b2ec9c3a3538fcf/components/econet/econet.cpp#L484

**Comment by tronikos** [comment]
I've already done this locally as part of #42. Need to do some more testing before I send a PR. I've also changed the logic of trying to pick a good time and it doesn't seem I get any more messages with crc16 mismatches.

**Comment by stockmopar** [comment]
What logic are you proposing to change to pick a good time?

**Comment by tronikos** [comment]
I'll add you as reviewer. The main issue of the current implementation is it can send a message in the middle of receiving a message. With my changes it will wait for partially received message to be fully received or timed out.
