### ISSUE TITLE
Add Wiki Content on Converting from Watt to kWH Power Consumption

### ISSUE THREAD

**Issue by barndawgie** [esphome-econet/esphome-econet#62]

**Comment by tronikos** [comment]
Good idea. I've personally created a helper left Riemann sum integral sensor and add that in my energy dashboard individual devices.

**Comment by barndawgie** [comment]
Created this page: https://github.com/esphome-econet/esphome-econet/wiki/Monitoring-Power-Consumption-in-kWh
